### PR TITLE
Check item.payload.docs is iterable before iterating

### LINKED ISSUE #39: putAll operation index must handle invalid entries
https://github.com/orbitdb/orbit-db-docstore/blob/b522ab298f95d9b0ff0e94beb4f5216c374860a5/src/DocumentIndex.js#L16-L26
In the state reducer of docstores updateIndex method, an invalid entry could be maliciously advertised to crash the method. This would likely result in the index state never being able to be update past the malicious entry. 
A check should be added that makes sure item.payload.docs is iterable or an array (e.g. `item.payload.docs[Symbol.iterator]` or `Array.isArray(item.payload.docs)`).

### PR DESCRIPTION
**Pull request by phillmac**
Fixes #39

### CODE REVIEW

File: src/DocumentIndex.js [hunk 1]
```diff
@@ -13,9 +13,9 @@ class DocumentIndex {
 
   updateIndex (oplog, onProgressCallback) {
     const reducer = (handled, item, idx) => {
-      if (item.payload.op === 'PUTALL') {
+      if (item.payload.op === 'PUTALL' && item.payload.docs[Symbol.iterator]) {
         for (const doc of item.payload.docs) {
-          if (handled[doc.key] !== true) {
+          if (doc && handled[doc.key] !== true) {
```
Comment (aphelionz) [inline src/DocumentIndex.js:18]: Which case is this checking for, will one of the iterable results be null or undefined?

Comment (phillmac) [reply src/DocumentIndex.js:18]: Yes. as per @tabcat the assumption is that someone maliciously creates a payload that has `doc` objects constructed in that fashion

**Comment by aphelionz** [comment]
@phillmac Looks good. Please confirm that the `orbitdb/orbit-db` tests pass successfully with this and I'll approve.
